### ISSUE TITLE
可能是blast的原因

### ISSUE THREAD

**Issue by karmen-cc** [guokai8/seq2Fun#1]
按照示例数据：
ann <- seq2fun(query = seqs, db = db, type = "blastp", evalue = 1e-10, num_threads = 2)

Error: Too many positional arguments (1), the offending value: >
Error:  (CArgException::eSynopsis) Too many positional arguments (1), the offending value: >
Finish blast  C:\PROGRA~1\NCBI\BLAST-~1.0_\bin\blastp.exe  ......
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'C:\Users\ADMINI~1\AppData\Local\Temp\RtmpoHEesX/file1a24559e7692.txt': No such file or directory

**Comment by guokai8** [comment]
我没有在windows下面测试过，你提供下你的sessionInfo
